# Generated by Django 5.1.3 on 2024-11-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_icecream_iceshop_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='oksvords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('osnovatel', models.CharField(max_length=100)),
                ('cost_of_semestr', models.DecimalField(decimal_places=5, max_digits=10)),
                ('idstudenta', models.ManyToManyField(to='app.students')),
            ],
        ),
    ]
