# Generated by Django 5.1.3 on 2024-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_students_oksvords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('childrenn', models.ManyToManyField(to='app.children')),
            ],
        ),
        migrations.DeleteModel(
            name='oksvords',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
